apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - generator.yaml

# Small customization example: add common labels to all generated resources
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: opendatahub
